### Obtencion de toda la lista de productos de la BD.
GET http://localhost:3000/products

### Obtencion de un producto en particular.
GET http://localhost:3000/products/2

### Creacion de un producto.
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Clousure",
  "price": 35.20,
  "quantity": 4
}

### Eliminacion de un producto.
DELETE http://localhost:3000/products/15

### Modificacion de un producto.
PUT http://localhost:3000/products/12
Content-Type: application/json

{
  "quantity":6
}