### Obtencion de toda la lista de productos de la BD.
GET http://localhost:3000/products

### Obtencion de un producto en particular.
GET http://localhost:3000/products/2

### Creacion de un producto.
POST http://localhost:3000/products/add
Content-Type: application/json

{
  "name": "Kit de Limpieza",
  "price": 2,
  "quantity": 4
}

### Eliminacion de un producto.
DELETE http://localhost:3000/products/15

### Modificacion de un producto.
PUT http://localhost:3000/products/12
Content-Type: application/json

{
  "quantity":6
}



### Obtencion de toda la lista de ventas de la BD.
GET http://localhost:3000/sales

### Obtencion de una venta en particular.
GET http://localhost:3000/sales/4

### Creacion de una venta.
POST http://localhost:3000/sales/add
Content-Type: application/json

{
  "productID": 2,
  "quantity": 2
}

### Eliminacion de una venta.
DELETE http://localhost:3000/sales/12

### Modificacion de una venta.
PUT http://localhost:3000/sales/12
Content-Type: application/json

{
  "quantity_sold":3
}